[package]
name = "quote-value"
version = "0.1.1"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "1"

[dependencies.quote-value-derive]
path = "../quote-value-derive"
version = "0.1.1"
